pipeline:
  name: AWS EKS
  identifier: AWS_EKS
  projectIdentifier: Femi_Sandbox
  orgIdentifier: sandbox
  tags: {}
  stages:
    - stage:
        name: Spin Up Cluster
        identifier: Spin_Up_Cluster
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: AWS_EKS
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMApproval
                  name: IaCM Approval
                  identifier: IaCM_Approval
                  spec:
                    autoApprove: false
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 2h
                  spec:
                    command: apply
        tags: {}
