apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    pr-commit-sha: ae28cad115834397d6fc107be21cfe58216e1fa7
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
